#!/bin/bash

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

if ! bspc wm -g &>/dev/null; then
  exit 1
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

./colors

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer true

bspc rule -a stalonetray state=floating manage=off

#
# danie
#
bspc rule -a alacritty desktop='^1' 
bspc rule -a firefox-nightly desktop='^2'
bspc rule -a spotify desktop='^5'

#
# cubum
#
bspc rule -a firefox desktop='^3' state=floating follow=on
bspc rule -a virt-viewer desktop='^4' 

#
# main
# 
bspc rule -a pavucontrol state=floating
bspc rule -a "VirtualBox Manager" state=floating
bspc rule -a "unetbootin.elf" state=floating
bspc rule -a "Places" state=floating

~/projects/bspi/bspi_listen >/dev/null 2>&1 &

notify-send -u low "bspwm loaded successfully"
